name: Compile8

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
# ============================================================
# 1. Build ── 針對三大 OS 編譯並產生可執行檔（不手動 zip）
# ============================================================
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        py: ['tiger']
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Derive short commit SHA
      id: vars
      shell: bash
      run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> "$GITHUB_ENV"

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pyinstaller onnxruntime

    - name: PyInstaller
      shell: bash
      run: |
        pyinstaller -c -p ./tigerbx \
          --additional-hooks-dir=./pyinstaller_hooks \
          --icon=./tigerbx/exe/ico.ico \
          -F ./tigerbx/${{ matrix.py }}.py

    - name: Prepare release folder
      shell: bash
      run: |
        mkdir release
        if [[ "$RUNNER_OS" == "Windows" ]]; then
          cp dist/* release/
        else
          mv dist/* release/
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.os }}-${{ env.SHORT_SHA }}
        path: release/

# ============================================================
# 2. Release ── 將資料夾壓成 zip 再發布
# ============================================================
  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: List downloaded files
      run: |
        echo "=== artifacts/ ==="
        tree -L 2 artifacts || true

    # ⬇️ 新增：把每個 release-* 資料夾壓成同名 .zip
    - name: Zip release artifacts
      run: |
        sudo apt-get update -y && sudo apt-get install -y zip
        for dir in artifacts/release-*; do
          zip -r "${dir}.zip" "$dir"
        done

    - name: Create draft GitHub Release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ github.run_number }}
        name: Release ${{ github.run_number }}
        draft: true
        artifacts: artifacts/release-*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
